dist: trusty

sudo: false

language: node_js

dist: bionic

node_js:
  - "10.15.3"
  - "stable"

cache:
  npm: true
  directories:
    - node_modules

addons:
  chrome: stable

services:
  - docker

script:
  - ./build.sh

matrix:
  allow_failures:
    - node_js: "stable"
